# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issue_comment:
    types: [created, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  parse_pr_info:
    if: github.event.comment.body == 'GitHub, generate web site'
          || github.event.comment.body == 'GitHub, generate website'
          || github.event.comment.body == 'GitHub, generate site'
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.ref }}

    steps:
      - uses: khan/pull-request-comment-trigger@master
        name: React with rocket on run
        with:
          trigger: ','
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo We print it here for this action to work'
        if: 'true'

  # This workflow contains a single job called "build"
  generate_site:
    needs: parse_pr_info
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin git@github.com:${github_token}/stonks-frontend.git
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}

    - name: Output
      uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Link to site : https://lnmiit-coding.github.io/stonks-frontend'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

